/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas.Administracion;

import Acciones.ClientesHabitualesService;
import Acciones.EmpleadoService;
import Domain.Empleado;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author miguel
 * Ventana grafica que permite al usuario administrar a los distintos empleados
 * 
 */
public class AdministracionEmpleados extends javax.swing.JFrame {

    /**
     * Creates new form AdministracionClientes
     */
    public AdministracionEmpleados() {
        initComponents();
        this.setTitle("Administracion Empleados");
        try{
            Toolkit mipantalla=Toolkit.getDefaultToolkit();
            Image miicono = mipantalla.getImage("src/main/java/imagenes/cajaregistradora.png");
            setIconImage(miicono);
        }catch(Exception e){
            System.out.println("Icono no encontrado : "+e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Contenedor = new javax.swing.JPanel();
        ContenedorListado = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEmpleados = new javax.swing.JTable();
        Enunciado2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        Enunciado = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        nombreTXT = new javax.swing.JTextField();
        DNITXT = new javax.swing.JTextField();
        labelDNI = new javax.swing.JLabel();
        emailTXT = new javax.swing.JTextField();
        labelEmail = new javax.swing.JLabel();
        telefonoTXT = new javax.swing.JTextField();
        labelTelefono = new javax.swing.JLabel();
        BtnModificar = new javax.swing.JButton();
        BtnBorrar = new javax.swing.JButton();
        BtnAñadir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Contenedor.setBackground(new java.awt.Color(94, 172, 255));

        ContenedorListado.setBackground(new java.awt.Color(137, 169, 204));
        ContenedorListado.setForeground(new java.awt.Color(204, 204, 204));

        tablaEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "idCliente", "Nombre", "DNI", "Telefono", "Email"
            }
        ));
        jScrollPane1.setViewportView(tablaEmpleados);

        Enunciado2.setFont(new java.awt.Font("BIZ UDMincho Medium", 1, 18)); // NOI18N
        Enunciado2.setText("Listado Empleados");

        jButton4.setBackground(new java.awt.Color(185, 145, 61));
        jButton4.setFont(new java.awt.Font("BIZ UDMincho Medium", 1, 11)); // NOI18N
        jButton4.setText("Listado");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ContenedorListadoLayout = new javax.swing.GroupLayout(ContenedorListado);
        ContenedorListado.setLayout(ContenedorListadoLayout);
        ContenedorListadoLayout.setHorizontalGroup(
            ContenedorListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContenedorListadoLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(ContenedorListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Enunciado2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );
        ContenedorListadoLayout.setVerticalGroup(
            ContenedorListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorListadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Enunciado2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        Enunciado.setFont(new java.awt.Font("BIZ UDMincho Medium", 1, 18)); // NOI18N
        Enunciado.setText("Gestion de Empleados");

        labelNombre.setFont(new java.awt.Font("BIZ UDMincho Medium", 1, 14)); // NOI18N
        labelNombre.setText("Nombre:");

        nombreTXT.setFont(new java.awt.Font("BIZ UDMincho Medium", 0, 14)); // NOI18N

        DNITXT.setFont(new java.awt.Font("BIZ UDMincho Medium", 0, 14)); // NOI18N

        labelDNI.setFont(new java.awt.Font("BIZ UDMincho Medium", 1, 14)); // NOI18N
        labelDNI.setText("DNI:");

        emailTXT.setFont(new java.awt.Font("BIZ UDMincho Medium", 0, 14)); // NOI18N

        labelEmail.setFont(new java.awt.Font("BIZ UDMincho Medium", 1, 14)); // NOI18N
        labelEmail.setText("Email:");

        telefonoTXT.setFont(new java.awt.Font("BIZ UDMincho Medium", 0, 14)); // NOI18N

        labelTelefono.setFont(new java.awt.Font("BIZ UDMincho Medium", 1, 14)); // NOI18N
        labelTelefono.setText("Telefono:");

        BtnModificar.setBackground(new java.awt.Color(185, 145, 61));
        BtnModificar.setFont(new java.awt.Font("BIZ UDMincho Medium", 1, 11)); // NOI18N
        BtnModificar.setText("Modificar");
        BtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarActionPerformed(evt);
            }
        });

        BtnBorrar.setBackground(new java.awt.Color(185, 145, 61));
        BtnBorrar.setFont(new java.awt.Font("BIZ UDMincho Medium", 1, 11)); // NOI18N
        BtnBorrar.setText("Borrar");
        BtnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBorrarActionPerformed(evt);
            }
        });

        BtnAñadir.setBackground(new java.awt.Color(185, 145, 61));
        BtnAñadir.setFont(new java.awt.Font("BIZ UDMincho Medium", 1, 11)); // NOI18N
        BtnAñadir.setText("Añadir");
        BtnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAñadirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ContenedorLayout = new javax.swing.GroupLayout(Contenedor);
        Contenedor.setLayout(ContenedorLayout);
        ContenedorLayout.setHorizontalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContenedorLayout.createSequentialGroup()
                        .addComponent(Enunciado, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(ContenedorLayout.createSequentialGroup()
                        .addComponent(labelDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DNITXT))
                    .addGroup(ContenedorLayout.createSequentialGroup()
                        .addComponent(labelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(emailTXT))
                    .addGroup(ContenedorLayout.createSequentialGroup()
                        .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nombreTXT))
                    .addGroup(ContenedorLayout.createSequentialGroup()
                        .addComponent(labelTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(telefonoTXT))
                    .addGroup(ContenedorLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(BtnAñadir, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(245, 245, 245)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ContenedorListado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ContenedorLayout.setVerticalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ContenedorListado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ContenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Enunciado, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DNITXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefonoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAñadirActionPerformed

        Empleado empleado = new Empleado();
        EmpleadoService es = new EmpleadoService();
        empleado.setNombre(nombreTXT.getText()); empleado.setDNI(DNITXT.getText());
        empleado.setEmail(emailTXT.getText()); empleado.setTelefono(telefonoTXT.getText());
        try{
            es.añadirEmpleado(empleado);
        }catch(SQLException e){
            System.out.println("Error al añadir empleado "+e);
        }
        try {
            es.tablaempleados(tablaEmpleados);
        } catch (SQLException ex) {
            System.out.println("Error en actualizacion automatica");
        }
    }//GEN-LAST:event_BtnAñadirActionPerformed

    private void BtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarActionPerformed

        int id = devolverid();
        
        Empleado empleado = new Empleado();
        EmpleadoService es = new EmpleadoService();
        empleado.setIdempleado(id); empleado.setEmail(emailTXT.getText()); empleado.setTelefono(telefonoTXT.getText());
        
        try{
            es.modificarempleado(empleado);
        }catch(SQLException e){
            System.out.println("Error en modificacion de empleado "+e);
        }
        try {
            es.tablaempleados(tablaEmpleados);
        } catch (SQLException ex) {
            System.out.println("Error en actualizacion automatica");
        }
    }//GEN-LAST:event_BtnModificarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        EmpleadoService es = new EmpleadoService();
        try {
            es.tablaempleados(tablaEmpleados);
        } catch (SQLException ex) {
            System.out.println("Error en actualizacion automatica");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void BtnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBorrarActionPerformed
        
        int id = devolverid();
        Empleado empleado = new Empleado();
        EmpleadoService es = new EmpleadoService();
        empleado.setIdempleado(id);
        try{
            es.borrarempleado(empleado);
        }catch(SQLException e){
            System.out.println("Error al borrar empleado");
        }
        try {
            es.tablaempleados(tablaEmpleados);
        } catch (SQLException ex) {
            System.out.println("Error en actualizacion automatica");
        }
            
    }//GEN-LAST:event_BtnBorrarActionPerformed

    private int devolverid(){
        DefaultTableModel tm = (DefaultTableModel)tablaEmpleados.getModel();
        String dato = String.valueOf(tm.getValueAt(tablaEmpleados.getSelectedRow(), 0));
        int id = Integer.parseInt(dato);
        
        return id;
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministracionEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministracionEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministracionEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministracionEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministracionEmpleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAñadir;
    private javax.swing.JButton BtnBorrar;
    private javax.swing.JButton BtnModificar;
    private javax.swing.JPanel Contenedor;
    private javax.swing.JPanel ContenedorListado;
    private javax.swing.JTextField DNITXT;
    private javax.swing.JLabel Enunciado;
    private javax.swing.JLabel Enunciado2;
    private javax.swing.JTextField emailTXT;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelDNI;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelTelefono;
    private javax.swing.JTextField nombreTXT;
    private javax.swing.JTable tablaEmpleados;
    private javax.swing.JTextField telefonoTXT;
    // End of variables declaration//GEN-END:variables
}
