/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author migue
 */
public class Login extends javax.swing.JFrame {
    Toolkit mipantalla=Toolkit.getDefaultToolkit();
    Dimension pantalla = mipantalla.getScreenSize();
    private int alto = pantalla.height; private int ancho = pantalla.width;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setLocation(ancho/4,alto/4);
        //Un titulin rapido y un icono para que no nos salga la taza de cafe
        this.setTitle("Login");
        try{
            Image miicono = mipantalla.getImage("src/main/java/imagenes/cajaregistradora.png");
            setIconImage(miicono);
        }catch(Exception e){
            System.out.println("Icono no encontrado : "+e);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Marca = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        etiUsuario = new javax.swing.JLabel();
        passtext = new javax.swing.JPasswordField();
        btnEntrar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        etiPass = new javax.swing.JLabel();
        Usuariotext = new javax.swing.JTextField();
        jlabelfondo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setMinimumSize(new java.awt.Dimension(326, 555));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(94, 172, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Marca.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Marca.setForeground(new java.awt.Color(204, 102, 0));
        Marca.setText("QC");
        jPanel3.add(Marca);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 51, 0));
        jLabel1.setText("Relaxing cup and cafe con leche");
        jPanel3.add(jLabel1);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(60, 40, 210, 70);

        etiUsuario.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        etiUsuario.setText("Clave:");
        jPanel1.add(etiUsuario);
        etiUsuario.setBounds(70, 260, 80, 20);
        jPanel1.add(passtext);
        passtext.setBounds(70, 290, 200, 40);

        btnEntrar.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEntrar);
        btnEntrar.setBounds(100, 360, 120, 60);

        btnSalir.setText("Salir");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        jPanel1.add(btnSalir);
        btnSalir.setBounds(120, 430, 80, 40);

        etiPass.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        etiPass.setText("Usuario:");
        jPanel1.add(etiPass);
        etiPass.setBounds(70, 170, 80, 20);
        jPanel1.add(Usuariotext);
        Usuariotext.setBounds(70, 200, 200, 40);

        jlabelfondo.setLabelFor(Marca);
        jPanel1.add(jlabelfondo);
        jlabelfondo.setBounds(-10, 0, 340, 560);

        jPanel2.setBackground(new java.awt.Color(137, 169, 204));
        jPanel1.add(jPanel2);
        jPanel2.setBounds(160, 0, 170, 550);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 360, 563);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        // TODO add your handling code here:
        VentanaPrincipal vp = new VentanaPrincipal();
        vp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Marca;
    private javax.swing.JTextField Usuariotext;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel etiPass;
    private javax.swing.JLabel etiUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jlabelfondo;
    private javax.swing.JPasswordField passtext;
    // End of variables declaration//GEN-END:variables
}
