/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas.Pedidos;

import Acciones.ProductoService;
import Domain.Producto;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.SwingConstants;
import ventanas.VentanaPrincipal;

/**
 *
 * @author migue
 */
public class Bocadillos extends javax.swing.JPanel {
    Toolkit mipantalla = Toolkit.getDefaultToolkit();
    Dimension pantalla = mipantalla.getScreenSize();
    private int alto = pantalla.height; private int ancho = pantalla.width;
    DateTimeFormatter formatHora = DateTimeFormatter.ofPattern("HH:mm");
    
    /**
     * Creates new form Bocadillos
     */
    public Bocadillos() {
        initComponents();
        pintarFondoBocadillos();
    }
    
    //Metodo que pasa los datos de todos los botones
    private void pintarFondoBocadillos(){
        dibujar(BtnBritishBacon, "src/main/java/imagenes/Hamburguesas/bocadillo.png", "BritishBacon");
        dibujar(BtnPolloBacon, "src/main/java/imagenes/Hamburguesas/bocadillo.png", "PolloBacon");
        dibujar(BtnPolloPimiento, "src/main/java/imagenes/Hamburguesas/bocadillo.png", "PolloPimiento");
        dibujar(BtnSerrano, "src/main/java/imagenes/Hamburguesas/bocadillo.png", "Serrano");
        dibujar(BtnTortilla, "src/main/java/imagenes/Hamburguesas/bocadillo.png", "Tortilla");
        dibujar(BtnIberico, "src/main/java/imagenes/Hamburguesas/bocadillo.png", "Iberico");
        dibujar(BtnPulledPork, "src/main/java/imagenes/Hamburguesas/bocadillo.png", "PulledPorkBBQ");
    }
    
    //Metodo usado para dibujar los botones
    private void dibujar(JButton boton, String url, String texto){
        try{
            Image primera = mipantalla.getImage(url);
            ImageIcon segunda = new ImageIcon(primera);
            boton.setIcon(segunda);
            boton.setText(texto);
            boton.setHorizontalTextPosition(SwingConstants.CENTER);
            boton.setVerticalTextPosition(SwingConstants.BOTTOM);
        }catch(Exception e){
            System.out.println("Error en "+boton+" : "+e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        BtnBritishBacon = new javax.swing.JButton();
        BtnPolloBacon = new javax.swing.JButton();
        BtnPolloPimiento = new javax.swing.JButton();
        BtnSerrano = new javax.swing.JButton();
        BtnTortilla = new javax.swing.JButton();
        BtnPulledPork = new javax.swing.JButton();
        BtnIberico = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(137, 169, 204));

        BtnBritishBacon.setBackground(new java.awt.Color(185, 145, 61));
        BtnBritishBacon.setFont(new java.awt.Font("BIZ UDMincho Medium", 1, 14)); // NOI18N
        BtnBritishBacon.setText("BritishBacon");
        BtnBritishBacon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBritishBaconActionPerformed(evt);
            }
        });

        BtnPolloBacon.setBackground(new java.awt.Color(185, 145, 61));
        BtnPolloBacon.setFont(new java.awt.Font("BIZ UDMincho Medium", 1, 14)); // NOI18N
        BtnPolloBacon.setText("PolloBacon");
        BtnPolloBacon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPolloBaconActionPerformed(evt);
            }
        });

        BtnPolloPimiento.setBackground(new java.awt.Color(185, 145, 61));
        BtnPolloPimiento.setFont(new java.awt.Font("BIZ UDMincho Medium", 1, 14)); // NOI18N
        BtnPolloPimiento.setText("PolloPimientos");
        BtnPolloPimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPolloPimientoActionPerformed(evt);
            }
        });

        BtnSerrano.setBackground(new java.awt.Color(185, 145, 61));
        BtnSerrano.setFont(new java.awt.Font("BIZ UDMincho Medium", 1, 14)); // NOI18N
        BtnSerrano.setText("Serrano");
        BtnSerrano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSerranoActionPerformed(evt);
            }
        });

        BtnTortilla.setBackground(new java.awt.Color(185, 145, 61));
        BtnTortilla.setFont(new java.awt.Font("BIZ UDMincho Medium", 1, 14)); // NOI18N
        BtnTortilla.setText("Tortilla");
        BtnTortilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTortillaActionPerformed(evt);
            }
        });

        BtnPulledPork.setBackground(new java.awt.Color(185, 145, 61));
        BtnPulledPork.setFont(new java.awt.Font("BIZ UDMincho Medium", 1, 14)); // NOI18N
        BtnPulledPork.setText("PulledPorkBBQ");
        BtnPulledPork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPulledPorkActionPerformed(evt);
            }
        });

        BtnIberico.setBackground(new java.awt.Color(185, 145, 61));
        BtnIberico.setFont(new java.awt.Font("BIZ UDMincho Medium", 1, 14)); // NOI18N
        BtnIberico.setText("Iberico");
        BtnIberico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIbericoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 711, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(BtnBritishBacon, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(BtnPolloBacon, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(BtnPolloPimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(BtnSerrano, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(BtnTortilla, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(BtnIberico, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(BtnPulledPork, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(102, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 386, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(BtnTortilla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnSerrano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnPolloPimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnPolloBacon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnBritishBacon, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(BtnPulledPork, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnIberico, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(109, Short.MAX_VALUE)))
        );

        jScrollPane1.setViewportView(jPanel1);

        add(jScrollPane1, "card9");
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBritishBaconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBritishBaconActionPerformed
        // TODO add your handling code here:
        String descripcion = "British Bacon"; int id = 045;
        crearproducto(descripcion,id);
    }//GEN-LAST:event_BtnBritishBaconActionPerformed

    private void BtnPolloBaconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPolloBaconActionPerformed
        // TODO add your handling code here:
        String descripcion = "Pollo y Bacon"; int id = 046;
        crearproducto(descripcion, id);
    }//GEN-LAST:event_BtnPolloBaconActionPerformed

    private void BtnPolloPimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPolloPimientoActionPerformed
        // TODO add your handling code here:
        String descripcion = "Pollo y Pimiento"; int id = 047;
        crearproducto(descripcion, id);
    }//GEN-LAST:event_BtnPolloPimientoActionPerformed

    private void BtnSerranoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSerranoActionPerformed
        // TODO add your handling code here:
        String descripcion = "Serrano"; int id = 050;
        crearproducto(descripcion, id);
    }//GEN-LAST:event_BtnSerranoActionPerformed

    private void BtnTortillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTortillaActionPerformed
        // TODO add your handling code here:
        String descripcion = "Tortilla"; int id = 051;
        crearproducto(descripcion, id);
    }//GEN-LAST:event_BtnTortillaActionPerformed

    private void BtnPulledPorkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPulledPorkActionPerformed
        // TODO add your handling code here:
        String descripcion = "PulledPorkBBQ"; int id = 052;
        crearproducto(descripcion, id);
    }//GEN-LAST:event_BtnPulledPorkActionPerformed

    private void BtnIbericoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIbericoActionPerformed
        // TODO add your handling code here:
        String descripcion = "Iberico"; int id = 053;
        crearproducto(descripcion, id);
    }//GEN-LAST:event_BtnIbericoActionPerformed
    
    private void crearproducto(String descripcion, int id){
        try {
            String horaconsumicion = formatHora.format(LocalDateTime.now());
            Producto producto = new Producto();
            String clienteid = VentanaPrincipal.ClienteChoice.getSelectedItem();
            String empleado = VentanaPrincipal.VendedorChoice.getSelectedItem();
            int Ntiket = Integer.parseInt(VentanaPrincipal.ticketTXT.getText());
            ProductoService pd = new ProductoService();
            producto.setCantidad(1);producto.setDescripcion(descripcion);producto.setPrecio(2.00);
            if(VentanaPrincipal.promocion){
                double descuento = producto.getPrecio()*20/100;
                producto.setPrecio(producto.getPrecio()-descuento);
            }
            producto.setPrecioTotal(producto.getPrecio()); producto.setidProducto(id);
            pd.cestaCompra(VentanaPrincipal.cajapantalla);
            pd.comprobarcarrito(VentanaPrincipal.cajapantalla, producto, horaconsumicion, clienteid, empleado, Ntiket);
        } catch (SQLException ex) {
            System.out.println("Error al añadir producto "+ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBritishBacon;
    private javax.swing.JButton BtnIberico;
    private javax.swing.JButton BtnPolloBacon;
    private javax.swing.JButton BtnPolloPimiento;
    private javax.swing.JButton BtnPulledPork;
    private javax.swing.JButton BtnSerrano;
    private javax.swing.JButton BtnTortilla;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
