/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas.Pedidos;

import Acciones.ProductoService;
import Domain.Producto;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.SwingConstants;
import ventanas.VentanaPrincipal;

/**
 *
 * @author migue
 */
public class Cafes extends javax.swing.JPanel {
    Toolkit mipantalla=Toolkit.getDefaultToolkit();
    Dimension pantalla = mipantalla.getScreenSize();
    private int alto = pantalla.height; private int ancho = pantalla.width;
    DateTimeFormatter formatHora = DateTimeFormatter.ofPattern("HH:mm");
    
    /**
     * Creates new form Cafes
     */
    public Cafes() {
        
        initComponents();
        pintarFondoCafes();
    }
    
    //Metodo que pasa los datos de todos los botones
    private void pintarFondoCafes(){
        
        dibujar(BtnCafeSolo, "src/main/java/imagenes/cafes/cafesolo.png", "Cafe Solo");
        dibujar(BtnCafeconLeche, "src/main/java/imagenes/cafes/cafeconleche.png", "Cafe con Leche");
        dibujar(BtnRistretto, "src/main/java/imagenes/cafes/ristretto.png", "Cafe Ristretto");
        dibujar(BtnMacchiato, "src/main/java/imagenes/cafes/machiato.png", "Cafe Macchiato");
        dibujar(BtnCafeAmericano, "src/main/java/imagenes/cafes/cafeamericano.png", "Cafe Americano");
        dibujar(BtnCafeLargo, "src/main/java/imagenes/cafes/cafelungo.png", "Cafe Largo");
        dibujar(BtnCarajillo, "src/main/java/imagenes/cafes/carajillo.png", "Carajillo");
        dibujar(BtnBombon, "src/main/java/imagenes/cafes/cafebombon.png", "Cafe Bombon");
        dibujar(BtnCapuchino, "src/main/java/imagenes/cafes/capuchino.png", "Capuchino");
        dibujar(BtnMocca, "src/main/java/imagenes/cafes/mocca.png", "Cafe Mocca");
        dibujar(BtnCafeIrlandes, "src/main/java/imagenes/cafes/cafeirlandes.png", "Cafe irlandes");
        dibujar(BtnCafeVienes, "src/main/java/imagenes/cafes/cafevienes.png", "Cafe Vienès");
        dibujar(BtnCafeFrape, "src/main/java/imagenes/cafes/frappe.png", "Cafe Frappe");
        dibujar(BtnCafeFrio, "src/main/java/imagenes/cafes/cafefrio.png", "Cafe Azteca");
    
    }
    
    //Metodo usado para dibujar los botones
    private void dibujar(JButton boton, String url, String texto){
        try{
            Image primera = mipantalla.getImage(url);
            ImageIcon segunda = new ImageIcon(primera);
            boton.setIcon(segunda);
            boton.setText(texto);
            boton.setHorizontalTextPosition(SwingConstants.CENTER);
            boton.setVerticalTextPosition(SwingConstants.BOTTOM);
        }catch(Exception e){
            System.out.println("Error en "+boton+" : "+e);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        contenedorCafes1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        BtnCafeSolo = new javax.swing.JButton();
        BtnCafeconLeche = new javax.swing.JButton();
        BtnRistretto = new javax.swing.JButton();
        BtnMacchiato = new javax.swing.JButton();
        BtnCafeAmericano = new javax.swing.JButton();
        BtnMocca = new javax.swing.JButton();
        BtnCapuchino = new javax.swing.JButton();
        BtnBombon = new javax.swing.JButton();
        BtnCarajillo = new javax.swing.JButton();
        BtnCafeLargo = new javax.swing.JButton();
        BtnCafeFrio = new javax.swing.JButton();
        BtnCafeFrape = new javax.swing.JButton();
        BtnCafeVienes = new javax.swing.JButton();
        BtnCafeIrlandes = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(242, 152, 56));
        jPanel2.setLayout(new java.awt.CardLayout());
        jScrollPane2.setViewportView(jPanel2);

        setBackground(new java.awt.Color(242, 152, 56));
        setLayout(new java.awt.CardLayout());

        contenedorCafes1.setBackground(new java.awt.Color(137, 169, 204));
        contenedorCafes1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(242, 152, 56));
        jPanel3.setLayout(new java.awt.CardLayout());
        contenedorCafes1.add(jPanel3);
        jPanel3.setBounds(0, 0, 0, 0);

        BtnCafeSolo.setBackground(new java.awt.Color(185, 145, 61));
        BtnCafeSolo.setFont(new java.awt.Font("BIZ UDMincho Medium", 1, 14)); // NOI18N
        BtnCafeSolo.setToolTipText("");
        BtnCafeSolo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnCafeSolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCafeSoloActionPerformed(evt);
            }
        });
        contenedorCafes1.add(BtnCafeSolo);
        BtnCafeSolo.setBounds(260, 150, 110, 130);

        BtnCafeconLeche.setBackground(new java.awt.Color(185, 145, 61));
        BtnCafeconLeche.setFont(new java.awt.Font("BIZ UDMincho Medium", 1, 14)); // NOI18N
        BtnCafeconLeche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCafeconLecheActionPerformed(evt);
            }
        });
        contenedorCafes1.add(BtnCafeconLeche);
        BtnCafeconLeche.setBounds(500, 10, 110, 130);

        BtnRistretto.setBackground(new java.awt.Color(185, 145, 61));
        BtnRistretto.setFont(new java.awt.Font("BIZ UDMincho Medium", 1, 14)); // NOI18N
        BtnRistretto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRistrettoActionPerformed(evt);
            }
        });
        contenedorCafes1.add(BtnRistretto);
        BtnRistretto.setBounds(20, 150, 110, 130);

        BtnMacchiato.setBackground(new java.awt.Color(185, 145, 61));
        BtnMacchiato.setFont(new java.awt.Font("BIZ UDMincho Medium", 1, 14)); // NOI18N
        BtnMacchiato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMacchiatoActionPerformed(evt);
            }
        });
        contenedorCafes1.add(BtnMacchiato);
        BtnMacchiato.setBounds(140, 10, 110, 130);

        BtnCafeAmericano.setBackground(new java.awt.Color(185, 145, 61));
        BtnCafeAmericano.setFont(new java.awt.Font("BIZ UDMincho Medium", 1, 14)); // NOI18N
        BtnCafeAmericano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCafeAmericanoActionPerformed(evt);
            }
        });
        contenedorCafes1.add(BtnCafeAmericano);
        BtnCafeAmericano.setBounds(260, 10, 110, 130);

        BtnMocca.setBackground(new java.awt.Color(185, 145, 61));
        BtnMocca.setFont(new java.awt.Font("BIZ UDMincho Medium", 1, 14)); // NOI18N
        BtnMocca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMoccaActionPerformed(evt);
            }
        });
        contenedorCafes1.add(BtnMocca);
        BtnMocca.setBounds(380, 150, 110, 130);

        BtnCapuchino.setBackground(new java.awt.Color(185, 145, 61));
        BtnCapuchino.setFont(new java.awt.Font("BIZ UDMincho Medium", 1, 14)); // NOI18N
        BtnCapuchino.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnCapuchino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCapuchinoActionPerformed(evt);
            }
        });
        contenedorCafes1.add(BtnCapuchino);
        BtnCapuchino.setBounds(140, 290, 110, 130);

        BtnBombon.setBackground(new java.awt.Color(185, 145, 61));
        BtnBombon.setFont(new java.awt.Font("BIZ UDMincho Medium", 1, 14)); // NOI18N
        BtnBombon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBombonActionPerformed(evt);
            }
        });
        contenedorCafes1.add(BtnBombon);
        BtnBombon.setBounds(140, 150, 110, 130);

        BtnCarajillo.setBackground(new java.awt.Color(185, 145, 61));
        BtnCarajillo.setFont(new java.awt.Font("BIZ UDMincho Medium", 1, 14)); // NOI18N
        BtnCarajillo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnCarajilloMouseClicked(evt);
            }
        });
        contenedorCafes1.add(BtnCarajillo);
        BtnCarajillo.setBounds(20, 10, 110, 130);

        BtnCafeLargo.setBackground(new java.awt.Color(185, 145, 61));
        BtnCafeLargo.setFont(new java.awt.Font("BIZ UDMincho Medium", 1, 14)); // NOI18N
        BtnCafeLargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCafeLargoActionPerformed(evt);
            }
        });
        contenedorCafes1.add(BtnCafeLargo);
        BtnCafeLargo.setBounds(380, 10, 110, 130);

        BtnCafeFrio.setBackground(new java.awt.Color(185, 145, 61));
        BtnCafeFrio.setFont(new java.awt.Font("BIZ UDMincho Medium", 1, 14)); // NOI18N
        BtnCafeFrio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCafeFrioActionPerformed(evt);
            }
        });
        contenedorCafes1.add(BtnCafeFrio);
        BtnCafeFrio.setBounds(620, 150, 110, 130);

        BtnCafeFrape.setBackground(new java.awt.Color(185, 145, 61));
        BtnCafeFrape.setFont(new java.awt.Font("BIZ UDMincho Medium", 1, 14)); // NOI18N
        BtnCafeFrape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCafeFrapeActionPerformed(evt);
            }
        });
        contenedorCafes1.add(BtnCafeFrape);
        BtnCafeFrape.setBounds(500, 150, 110, 130);

        BtnCafeVienes.setBackground(new java.awt.Color(185, 145, 61));
        BtnCafeVienes.setFont(new java.awt.Font("BIZ UDMincho Medium", 1, 14)); // NOI18N
        BtnCafeVienes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCafeVienesActionPerformed(evt);
            }
        });
        contenedorCafes1.add(BtnCafeVienes);
        BtnCafeVienes.setBounds(620, 10, 110, 130);

        BtnCafeIrlandes.setBackground(new java.awt.Color(185, 145, 61));
        BtnCafeIrlandes.setFont(new java.awt.Font("BIZ UDMincho Medium", 1, 14)); // NOI18N
        BtnCafeIrlandes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCafeIrlandesActionPerformed(evt);
            }
        });
        contenedorCafes1.add(BtnCafeIrlandes);
        BtnCafeIrlandes.setBounds(20, 290, 110, 130);

        jScrollPane3.setViewportView(contenedorCafes1);

        add(jScrollPane3, "card3");
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCafeIrlandesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCafeIrlandesActionPerformed
        // TODO add your handling code here:
        String descripcion = "Irlandes"; int id = 015;
        crearproducto(descripcion, id);
         
            
    }//GEN-LAST:event_BtnCafeIrlandesActionPerformed

    private void BtnCapuchinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCapuchinoActionPerformed
        // TODO add your handling code here:
        String descripcion = "Capuchino"; int id = 016;
        crearproducto(descripcion, id);
    }//GEN-LAST:event_BtnCapuchinoActionPerformed

    private void BtnCarajilloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCarajilloMouseClicked
        // TODO add your handling code here:
        String descripcion = "Carajillo"; int id = 001;
        crearproducto(descripcion,id);
    }//GEN-LAST:event_BtnCarajilloMouseClicked

    private void BtnMacchiatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMacchiatoActionPerformed
        // TODO add your handling code here:
        String descripcion = "Machiato"; int id = 002;
        crearproducto (descripcion, id);
    }//GEN-LAST:event_BtnMacchiatoActionPerformed

    private void BtnCafeAmericanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCafeAmericanoActionPerformed
        // TODO add your handling code here:
        String descripcion = "Americano"; int id = 003;
        crearproducto(descripcion, id);
    }//GEN-LAST:event_BtnCafeAmericanoActionPerformed

    private void BtnCafeLargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCafeLargoActionPerformed
        // TODO add your handling code here:
        String descripcion = "Cafe largo"; int id = 004;
        crearproducto(descripcion, id);
    }//GEN-LAST:event_BtnCafeLargoActionPerformed

    private void BtnCafeconLecheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCafeconLecheActionPerformed
        // TODO add your handling code here:
        String descripcion = "Cafe leche"; int id = 005;
        crearproducto(descripcion, id);
    }//GEN-LAST:event_BtnCafeconLecheActionPerformed

    private void BtnCafeVienesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCafeVienesActionPerformed
        // TODO add your handling code here:
        String descripcion = "Vienes"; int id = 006;
        crearproducto(descripcion, id);
    }//GEN-LAST:event_BtnCafeVienesActionPerformed

    private void BtnRistrettoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRistrettoActionPerformed
        // TODO add your handling code here:
        String descripcion = "Ristretto"; int id = 007;
        crearproducto(descripcion, id);
    }//GEN-LAST:event_BtnRistrettoActionPerformed

    private void BtnBombonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBombonActionPerformed
        // TODO add your handling code here:
        String descripcion = "C. Bombon"; int id = 010;
        crearproducto(descripcion, id);
    }//GEN-LAST:event_BtnBombonActionPerformed

    private void BtnCafeSoloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCafeSoloActionPerformed
        // TODO add your handling code here:
        String descripcion = "Cafe Solo"; int id = 011;
        crearproducto(descripcion, id);
    }//GEN-LAST:event_BtnCafeSoloActionPerformed

    private void BtnMoccaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMoccaActionPerformed
        // TODO add your handling code here:
        String descripcion = "Mocca"; int id = 012;
        crearproducto(descripcion, id);
    }//GEN-LAST:event_BtnMoccaActionPerformed

    private void BtnCafeFrapeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCafeFrapeActionPerformed
        // TODO add your handling code here:
        String descripcion = "Frape"; int id = 013;
        crearproducto(descripcion, id);
    }//GEN-LAST:event_BtnCafeFrapeActionPerformed

    private void BtnCafeFrioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCafeFrioActionPerformed
        // TODO add your handling code here:
        String descripcion = "Cafe frio"; int id = 014;
        crearproducto(descripcion, id);
    }//GEN-LAST:event_BtnCafeFrioActionPerformed
    
    private void crearproducto(String descripcion, int id){
        
        try {
            String horaconsumicion = formatHora.format(LocalDateTime.now());
            Producto producto = new Producto();
            String clienteid = VentanaPrincipal.ClienteChoice.getSelectedItem();
            String empleado = VentanaPrincipal.VendedorChoice.getSelectedItem();
            int Ntiket = Integer.parseInt(VentanaPrincipal.ticketTXT.getText());
            ProductoService pd = new ProductoService();
            producto.setCantidad(1);producto.setDescripcion(descripcion);producto.setPrecio(1.00);
            if(VentanaPrincipal.promocion){
                double descuento = producto.getPrecio()*20/100;
                producto.setPrecio(producto.getPrecio()-descuento);
            }
            producto.setPrecioTotal(producto.getPrecio()); producto.setidProducto(id);
            pd.cestaCompra(VentanaPrincipal.cajapantalla);
            pd.comprobarcarrito(VentanaPrincipal.cajapantalla, producto, horaconsumicion, clienteid, empleado, Ntiket);
        } catch (SQLException ex) {
            System.out.println("Error al añadir producto "+ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBombon;
    private javax.swing.JButton BtnCafeAmericano;
    private javax.swing.JButton BtnCafeFrape;
    private javax.swing.JButton BtnCafeFrio;
    private javax.swing.JButton BtnCafeIrlandes;
    private javax.swing.JButton BtnCafeLargo;
    private javax.swing.JButton BtnCafeSolo;
    private javax.swing.JButton BtnCafeVienes;
    private javax.swing.JButton BtnCafeconLeche;
    private javax.swing.JButton BtnCapuchino;
    private javax.swing.JButton BtnCarajillo;
    private javax.swing.JButton BtnMacchiato;
    private javax.swing.JButton BtnMocca;
    private javax.swing.JButton BtnRistretto;
    private javax.swing.JPanel contenedorCafes1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
