/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas.Pedidos;

import Acciones.ProductoService;
import Domain.Producto;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.SwingConstants;
import ventanas.VentanaPrincipal;

/**
 *
 * @author migue
 */
public class Hamburguesas extends javax.swing.JPanel {
    Toolkit mipantalla = Toolkit.getDefaultToolkit();
    Dimension pantalla = mipantalla.getScreenSize();
    private int alto = pantalla.height; private int ancho = pantalla.width;
    DateTimeFormatter formatHora = DateTimeFormatter.ofPattern("HH:mm");

    /**
     * Creates new form Hamburguesas
     */
    public Hamburguesas() {
        initComponents();
        pintarFondoHamburguesas();
    }
    
    //Metodo que pasa los datos de todos los botones
    private void pintarFondoHamburguesas(){
        
        dibujar(BtnFondueBurger, "src/main/java/imagenes/Hamburguesas/Hamburguesa.png", "FondueBurguer");
        dibujar(BtnRebelWhopper, "src/main/java/imagenes/Hamburguesas/Hamburguesa.png", "RebelWhopper");
        dibujar(BtnWhopper, "src/main/java/imagenes/Hamburguesas/Hamburguesa.png", "Whopper");
        dibujar(BtnKingBacon, "src/main/java/imagenes/Hamburguesas/Hamburguesa.png", "KingBacon");
        dibujar(BtnKingHuevo, "src/main/java/imagenes/Hamburguesas/Hamburguesa.png", "KingHuevo");
        dibujar(BtnDobleCheeseBacon, "src/main/java/imagenes/Hamburguesas/Hamburguesa.png", "DobleCheeseBurger");
        dibujar(BtnBigKing, "src/main/java/imagenes/Hamburguesas/Hamburguesa.png", "BigKing");
        dibujar(BtnDobleWhopper, "src/main/java/imagenes/Hamburguesas/Hamburguesa.png", "DobleWhopper");
        dibujar(BtnWhopperJR, "src/main/java/imagenes/Hamburguesas/Hamburguesa.png", "WhopperJR");
        dibujar(BtnTripleWhopper, "src/main/java/imagenes/Hamburguesas/Hamburguesa.png", "TripleWhopper");
        dibujar(BtnSteakHouse, "src/main/java/imagenes/Hamburguesas/Hamburguesa.png", "SteakHouse");
        dibujar(BtnLongTexas, "src/main/java/imagenes/Hamburguesas/Hamburguesa.png", "LongTexas");
        dibujar(BtnDobleChessBurg, "src/main/java/imagenes/Hamburguesas/Hamburguesa.png", "DobleChessBurg");
        dibujar(BtnDobleBaconChess, "src/main/java/imagenes/Hamburguesas/Hamburguesa.png", "DobleBaconChess");
        
    }
    
    //Metodo usado para dibujar los botones
    private void dibujar(JButton boton, String url, String texto){
        try{
            Image primera = mipantalla.getImage(url);
            ImageIcon segunda = new ImageIcon(primera);
            boton.setIcon(segunda);
            boton.setText(texto);
            boton.setHorizontalTextPosition(SwingConstants.CENTER);
            boton.setVerticalTextPosition(SwingConstants.BOTTOM);
        }catch(Exception e){
            System.out.println("Error en "+boton+" : "+e);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        BtnFondueBurger = new javax.swing.JButton();
        BtnRebelWhopper = new javax.swing.JButton();
        BtnWhopper = new javax.swing.JButton();
        BtnKingBacon = new javax.swing.JButton();
        BtnKingHuevo = new javax.swing.JButton();
        BtnDobleCheeseBacon = new javax.swing.JButton();
        BtnLongTexas = new javax.swing.JButton();
        BtnSteakHouse = new javax.swing.JButton();
        BtnTripleWhopper = new javax.swing.JButton();
        BtnWhopperJR = new javax.swing.JButton();
        BtnDobleWhopper = new javax.swing.JButton();
        BtnBigKing = new javax.swing.JButton();
        BtnDobleChessBurg = new javax.swing.JButton();
        BtnDobleBaconChess = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(137, 169, 204));
        jPanel1.setLayout(null);

        BtnFondueBurger.setBackground(new java.awt.Color(185, 145, 61));
        BtnFondueBurger.setFont(new java.awt.Font("BIZ UDMincho Medium", 1, 14)); // NOI18N
        BtnFondueBurger.setText("Fondue Burger");
        BtnFondueBurger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnFondueBurgerMouseClicked(evt);
            }
        });
        jPanel1.add(BtnFondueBurger);
        BtnFondueBurger.setBounds(20, 10, 110, 130);

        BtnRebelWhopper.setBackground(new java.awt.Color(185, 145, 61));
        BtnRebelWhopper.setFont(new java.awt.Font("BIZ UDMincho Medium", 1, 14)); // NOI18N
        BtnRebelWhopper.setText("Rebel Woper");
        BtnRebelWhopper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRebelWhopperActionPerformed(evt);
            }
        });
        jPanel1.add(BtnRebelWhopper);
        BtnRebelWhopper.setBounds(140, 10, 110, 130);

        BtnWhopper.setBackground(new java.awt.Color(185, 145, 61));
        BtnWhopper.setFont(new java.awt.Font("BIZ UDMincho Medium", 1, 14)); // NOI18N
        BtnWhopper.setText("Whopper");
        BtnWhopper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnWhopperActionPerformed(evt);
            }
        });
        jPanel1.add(BtnWhopper);
        BtnWhopper.setBounds(260, 10, 110, 130);

        BtnKingBacon.setBackground(new java.awt.Color(185, 145, 61));
        BtnKingBacon.setFont(new java.awt.Font("BIZ UDMincho Medium", 1, 14)); // NOI18N
        BtnKingBacon.setText("King Bacon");
        BtnKingBacon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKingBaconActionPerformed(evt);
            }
        });
        jPanel1.add(BtnKingBacon);
        BtnKingBacon.setBounds(380, 10, 110, 130);

        BtnKingHuevo.setBackground(new java.awt.Color(185, 145, 61));
        BtnKingHuevo.setFont(new java.awt.Font("BIZ UDMincho Medium", 1, 14)); // NOI18N
        BtnKingHuevo.setText("King Huevo");
        BtnKingHuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKingHuevoActionPerformed(evt);
            }
        });
        jPanel1.add(BtnKingHuevo);
        BtnKingHuevo.setBounds(500, 10, 110, 130);

        BtnDobleCheeseBacon.setBackground(new java.awt.Color(185, 145, 61));
        BtnDobleCheeseBacon.setFont(new java.awt.Font("BIZ UDMincho Medium", 1, 14)); // NOI18N
        BtnDobleCheeseBacon.setText("DobleChessBacon");
        BtnDobleCheeseBacon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDobleCheeseBaconActionPerformed(evt);
            }
        });
        jPanel1.add(BtnDobleCheeseBacon);
        BtnDobleCheeseBacon.setBounds(620, 10, 110, 130);

        BtnLongTexas.setBackground(new java.awt.Color(185, 145, 61));
        BtnLongTexas.setFont(new java.awt.Font("BIZ UDMincho Medium", 1, 14)); // NOI18N
        BtnLongTexas.setText("LongTexas");
        BtnLongTexas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLongTexasActionPerformed(evt);
            }
        });
        jPanel1.add(BtnLongTexas);
        BtnLongTexas.setBounds(620, 150, 110, 130);

        BtnSteakHouse.setBackground(new java.awt.Color(185, 145, 61));
        BtnSteakHouse.setFont(new java.awt.Font("BIZ UDMincho Medium", 1, 14)); // NOI18N
        BtnSteakHouse.setText("SteakHouse");
        BtnSteakHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSteakHouseActionPerformed(evt);
            }
        });
        jPanel1.add(BtnSteakHouse);
        BtnSteakHouse.setBounds(500, 150, 110, 130);

        BtnTripleWhopper.setBackground(new java.awt.Color(185, 145, 61));
        BtnTripleWhopper.setFont(new java.awt.Font("BIZ UDMincho Medium", 1, 14)); // NOI18N
        BtnTripleWhopper.setText("TripleWoper");
        BtnTripleWhopper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTripleWhopperActionPerformed(evt);
            }
        });
        jPanel1.add(BtnTripleWhopper);
        BtnTripleWhopper.setBounds(380, 150, 110, 130);

        BtnWhopperJR.setBackground(new java.awt.Color(185, 145, 61));
        BtnWhopperJR.setFont(new java.awt.Font("BIZ UDMincho Medium", 1, 14)); // NOI18N
        BtnWhopperJR.setText("Woper Jr");
        BtnWhopperJR.setToolTipText("");
        BtnWhopperJR.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnWhopperJR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnWhopperJRActionPerformed(evt);
            }
        });
        jPanel1.add(BtnWhopperJR);
        BtnWhopperJR.setBounds(260, 150, 110, 130);

        BtnDobleWhopper.setBackground(new java.awt.Color(185, 145, 61));
        BtnDobleWhopper.setFont(new java.awt.Font("BIZ UDMincho Medium", 1, 14)); // NOI18N
        BtnDobleWhopper.setText("Doble woper");
        BtnDobleWhopper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDobleWhopperActionPerformed(evt);
            }
        });
        jPanel1.add(BtnDobleWhopper);
        BtnDobleWhopper.setBounds(140, 150, 110, 130);

        BtnBigKing.setBackground(new java.awt.Color(185, 145, 61));
        BtnBigKing.setFont(new java.awt.Font("BIZ UDMincho Medium", 1, 14)); // NOI18N
        BtnBigKing.setText("BigKing");
        BtnBigKing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBigKingActionPerformed(evt);
            }
        });
        jPanel1.add(BtnBigKing);
        BtnBigKing.setBounds(20, 150, 110, 130);

        BtnDobleChessBurg.setBackground(new java.awt.Color(185, 145, 61));
        BtnDobleChessBurg.setFont(new java.awt.Font("BIZ UDMincho Medium", 1, 14)); // NOI18N
        BtnDobleChessBurg.setText("DobleChessBurg");
        BtnDobleChessBurg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDobleChessBurgActionPerformed(evt);
            }
        });
        jPanel1.add(BtnDobleChessBurg);
        BtnDobleChessBurg.setBounds(20, 290, 110, 130);

        BtnDobleBaconChess.setBackground(new java.awt.Color(185, 145, 61));
        BtnDobleBaconChess.setFont(new java.awt.Font("BIZ UDMincho Medium", 1, 14)); // NOI18N
        BtnDobleBaconChess.setText("DobleBaconChes");
        BtnDobleBaconChess.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnDobleBaconChess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDobleBaconChessActionPerformed(evt);
            }
        });
        jPanel1.add(BtnDobleBaconChess);
        BtnDobleBaconChess.setBounds(140, 290, 110, 130);

        jScrollPane1.setViewportView(jPanel1);

        add(jScrollPane1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void BtnFondueBurgerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnFondueBurgerMouseClicked
        // TODO add your handling code here:
        String descripcion = "Fondue Burger"; int id = 027;
        crearproducto(descripcion,id);
    }//GEN-LAST:event_BtnFondueBurgerMouseClicked

    private void BtnRebelWhopperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRebelWhopperActionPerformed
        // TODO add your handling code here:
        String descripcion = "Rebel Whopper"; int id = 030;
        crearproducto (descripcion, id);
    }//GEN-LAST:event_BtnRebelWhopperActionPerformed

    private void BtnWhopperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnWhopperActionPerformed
        // TODO add your handling code here:
        String descripcion = "Whopper"; int id = 031;
        crearproducto(descripcion, id);
    }//GEN-LAST:event_BtnWhopperActionPerformed

    private void BtnKingBaconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKingBaconActionPerformed
        // TODO add your handling code here:
        String descripcion = "KingBacon"; int id = 032;
        crearproducto(descripcion, id);
    }//GEN-LAST:event_BtnKingBaconActionPerformed

    private void BtnKingHuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKingHuevoActionPerformed
        // TODO add your handling code here:
        String descripcion = "King Huevo"; int id = 033;
        crearproducto(descripcion, id);
    }//GEN-LAST:event_BtnKingHuevoActionPerformed

    private void BtnDobleCheeseBaconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDobleCheeseBaconActionPerformed
        // TODO add your handling code here:
        String descripcion = "DobleCheeseBacon"; int id = 034;
        crearproducto(descripcion, id);
    }//GEN-LAST:event_BtnDobleCheeseBaconActionPerformed

    private void BtnLongTexasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLongTexasActionPerformed
        // TODO add your handling code here:
        String descripcion = "LongTexas"; int id = 035;
        crearproducto(descripcion, id);
    }//GEN-LAST:event_BtnLongTexasActionPerformed

    private void BtnSteakHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSteakHouseActionPerformed
        // TODO add your handling code here:
        String descripcion = "SteakHouse"; int id = 036;
        crearproducto(descripcion, id);
    }//GEN-LAST:event_BtnSteakHouseActionPerformed

    private void BtnTripleWhopperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTripleWhopperActionPerformed
        // TODO add your handling code here:
        String descripcion = "TripleWhopper"; int id = 037;
        crearproducto(descripcion, id);
    }//GEN-LAST:event_BtnTripleWhopperActionPerformed

    private void BtnWhopperJRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnWhopperJRActionPerformed
        // TODO add your handling code here:
        String descripcion = "WhopperJR"; int id = 040;
        crearproducto(descripcion, id);
    }//GEN-LAST:event_BtnWhopperJRActionPerformed

    private void BtnDobleWhopperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDobleWhopperActionPerformed
        // TODO add your handling code here:
        String descripcion = "DobleWhopper"; int id = 041;
        crearproducto(descripcion, id);
    }//GEN-LAST:event_BtnDobleWhopperActionPerformed

    private void BtnBigKingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBigKingActionPerformed
        // TODO add your handling code here:
        String descripcion = "BigKing"; int id = 042;
        crearproducto(descripcion, id);
    }//GEN-LAST:event_BtnBigKingActionPerformed

    private void BtnDobleChessBurgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDobleChessBurgActionPerformed
        // TODO add your handling code here:
        String descripcion = "DobleChessBurg"; int id = 043;
        crearproducto(descripcion, id);
    }//GEN-LAST:event_BtnDobleChessBurgActionPerformed

    private void BtnDobleBaconChessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDobleBaconChessActionPerformed
        // TODO add your handling code here:
        String descripcion = "DobleBaconChess"; int id = 044;
        crearproducto(descripcion, id);
    }//GEN-LAST:event_BtnDobleBaconChessActionPerformed

    private void crearproducto(String descripcion, int id){
        try {
            String horaconsumicion = formatHora.format(LocalDateTime.now());
            Producto producto = new Producto();
            String clienteid = VentanaPrincipal.ClienteChoice.getSelectedItem();
            String empleado = VentanaPrincipal.VendedorChoice.getSelectedItem();
            int Ntiket = Integer.parseInt(VentanaPrincipal.ticketTXT.getText());
            ProductoService pd = new ProductoService();
            producto.setCantidad(1);producto.setDescripcion(descripcion);producto.setPrecio(3.00);
            if(VentanaPrincipal.promocion){
                double descuento = producto.getPrecio()*20/100;
                producto.setPrecio(producto.getPrecio()-descuento);
            }
            producto.setPrecioTotal(producto.getPrecio()); producto.setidProducto(id);
            pd.cestaCompra(VentanaPrincipal.cajapantalla);
            pd.comprobarcarrito(VentanaPrincipal.cajapantalla, producto, horaconsumicion, clienteid, empleado, Ntiket);
        } catch (SQLException ex) {
            System.out.println("Error al añadir producto "+ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBigKing;
    private javax.swing.JButton BtnDobleBaconChess;
    private javax.swing.JButton BtnDobleCheeseBacon;
    private javax.swing.JButton BtnDobleChessBurg;
    private javax.swing.JButton BtnDobleWhopper;
    private javax.swing.JButton BtnFondueBurger;
    private javax.swing.JButton BtnKingBacon;
    private javax.swing.JButton BtnKingHuevo;
    private javax.swing.JButton BtnLongTexas;
    private javax.swing.JButton BtnRebelWhopper;
    private javax.swing.JButton BtnSteakHouse;
    private javax.swing.JButton BtnTripleWhopper;
    private javax.swing.JButton BtnWhopper;
    private javax.swing.JButton BtnWhopperJR;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
